[build-system]
requires = [
   "setuptools==69.1.1",
   "wheel==0.42.0",
   "tomli==2.0.1; python_version<'3.11'",
   "packaging==23.2",
   "json-with-comments==1.2.3",
]

[project]
name = "MusicBot-DB"
description = "Package that installs DB library and jsonc as dependencies"
version = "0.0.3"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = "db.txt"}
